export const IS_NAV_EXPANDED = "IS_NAV_EXPANDED";

export const GET_ALL_FORM_SUCCESS = "GET_ALL_FORM_SUCCESS";
export const GET_ALL_FORM_FAILURE = "GET_ALL_FORM_FAILURE";

export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORM_FAILURE = "GET_FORM_FAILURE";

export const ADD_FORM_SUCCESS = "ADD_FORM_SUCCESS";
export const ADD_FORM_FAILURE = "ADD_FORM_FAILURE";

export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS";
export const UPDATE_FORM_FAILURE = "UPDATE_FORM_FAILURE";

export const DELETE_FORM_SUCCESS = "DELETE_FORM_SUCCESS";
export const DELETE_FORM_FAILURE = "DELETE_FORM_FAILURE";

export const ADD_DOWNLOAD_PDF_SUCCESS = "ADD_DOWNLOAD_PDF_SUCCESS";
export const ADD_DOWNLOAD_PDF_FAILURE = "ADD_DOWNLOAD_PDF_FAILURE";